apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-html-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>WebApp with PostgreSQL</title>
    </head>
    <body>
        <h1>Welcome to Our Web Application</h1>
        <p>This application is connected to a PostgreSQL database.</p>
        <p>Application version: {{ .Chart.AppVersion }}</p>
    </body>
    </html>
