apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-db
  labels:
    app: {{ .Chart.Name }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-db
    spec:
      containers:
      - name: db
        image: {{ .Values.db.image }}
        ports:
        - containerPort: {{ .Values.db.port }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.db.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.db.password }}
        - name: POSTGRES_DB
          value: {{ .Values.db.database }}
