apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-web-service
spec:
  type: {{ .Values.web.serviceType }}
  ports:
  - port: 80
    targetPort: {{ .Values.web.port }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Chart.Name }}-web
