# user-management-app/k8s/argocd-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-management-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/your-repo/user-management-app.git
    targetRevision: HEAD
    path: helm
    helm:
      releaseName: user-management-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
