apiVersion: v2
name: webapp
description: A Helm chart for a web application with PostgreSQL
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: postgresql
    version: 12.1.6
    repository: https://charts.bitnami.com/bitnami
