apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webapp.fullname" . }}-web-content
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Login App with PostgreSQL</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                background-color: #f4f4f4;
                margin: 0;
                padding: 0;
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
            }
            .container {
                background: #fff;
                padding: 20px;
                border-radius: 5px;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
                width: 300px;
            }
            h1 {
                text-align: center;
                color: #333;
            }
            .form-group {
                margin-bottom: 15px;
            }
            label {
                display: block;
                margin-bottom: 5px;
                color: #555;
            }
            input[type="text"],
            input[type="password"] {
                width: 100%;
                padding: 8px;
                border: 1px solid #ddd;
                border-radius: 4px;
                box-sizing: border-box;
            }
            button {
                width: 100%;
                padding: 10px;
                background-color: #5cb85c;
                border: none;
                border-radius: 4px;
                color: white;
                cursor: pointer;
            }
            button:hover {
                background-color: #4cae4c;
            }
            .message {
                margin-top: 15px;
                text-align: center;
                color: #777;
            }
            .logout {
                display: none;
                text-align: center;
                margin-top: 15px;
            }
            .logout a {
                color: #d9534f;
                text-decoration: none;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Login</h1>
            <div id="login-form">
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" id="username" placeholder="Enter username">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" id="password" placeholder="Enter password">
                </div>
                <button onclick="login()">Login</button>
                <div class="message" id="message"></div>
            </div>
            <div class="logout" id="logout-section">
                <p>Welcome, <span id="logged-in-user"></span>!</p>
                <a href="#" onclick="logout()">Logout</a>
            </div>
        </div>

        <script>
            function login() {
                const username = document.getElementById('username').value;
                const password = document.getElementById('password').value;
                
                // In a real app, you would make an API call to your backend
                // For this example, we'll simulate a successful login
                if (username && password) {
                    document.getElementById('login-form').style.display = 'none';
                    document.getElementById('logout-section').style.display = 'block';
                    document.getElementById('logged-in-user').textContent = username;
                    document.getElementById('message').textContent = '';
                    
                    // Simulate storing session data
                    localStorage.setItem('loggedIn', 'true');
                    localStorage.setItem('username', username);
                } else {
                    document.getElementById('message').textContent = 'Please enter both username and password';
                    document.getElementById('message').style.color = '#d9534f';
                }
            }
            
            function logout() {
                document.getElementById('login-form').style.display = 'block';
                document.getElementById('logout-section').style.display = 'none';
                document.getElementById('username').value = '';
                document.getElementById('password').value = '';
                
                // Simulate clearing session data
                localStorage.removeItem('loggedIn');
                localStorage.removeItem('username');
            }
            
            // Check if user is already logged in
            window.onload = function() {
                if (localStorage.getItem('loggedIn') === 'true') {
                    document.getElementById('login-form').style.display = 'none';
                    document.getElementById('logout-section').style.display = 'block';
                    document.getElementById('logged-in-user').textContent = localStorage.getItem('username');
                }
            };
        </script>
    </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webapp.fullname" . }}-web-config
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location /api/ {
            proxy_pass http://backend-service:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
