apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webapp.fullname" . }}-web
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "webapp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "webapp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: web-content
              mountPath: /usr/share/nginx/html
            - name: config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          env:
            - name: DB_HOST
              value: {{ include "webapp.fullname" . }}-postgresql
            - name: DB_NAME
              value: {{ .Values.postgresql.global.postgresql.auth.database }}
            - name: DB_USER
              value: {{ .Values.postgresql.global.postgresql.auth.username }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "webapp.fullname" . }}-postgresql
                  key: postgres-password
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
      volumes:
        - name: web-content
          configMap:
            name: {{ include "webapp.fullname" . }}-web-content
        - name: config
          configMap:
            name: {{ include "webapp.fullname" . }}-web-config
