apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ugardi/demo_app_argoCD.git # https://github.com/your-repo/webapp-helm.git
    targetRevision: HEAD
    path: webapp-1
    helm:
      values: |
        web:
          ingress:
            hosts:
<<<<<<< HEAD
              - host: webapp.172.214.68.113.nip.io #webapp-1.yourdomain.com
=======
              - host:  webapp.172.214.68.113.nip.io  #webapp.yourdomain.com
>>>>>>> 1f4189acf0b130683a5a4d150fced13fd41b795e
                paths:
                  - path: /
                    pathType: Prefix
  destination:
    server: https://kubernetes.default.svc
    namespace: webapp1 #default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
