apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-repo/webapp-helm.git
    targetRevision: HEAD
    path: webapp-1
    helm:
      values: |
        web:
          ingress:
            hosts:
              - host:  webapp.172.214.68.113.nip.io  #webapp.yourdomain.com
                paths:
                  - path: /
                    pathType: Prefix
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
