apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: web-app
  source:
    repoURL: https://github.com/your-org/web-app-argo.git
    targetRevision: HEAD
    path: frontend/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: web-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
