apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-management.fullname" . }}
  labels:
    {{- include "user-management.labels" . | nindent 4 }}
data:
  APP_DEBUG: {{ .Values.app.config.debug | quote }}
