apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "user-management.fullname" . }}-db-init
  labels:
    {{- include "user-management.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "user-management.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: db-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["python", "-c", "from app import app, db; app.app_context().push(); db.create_all()"]
          env:
            - name: DATABASE_URL
              value: postgresql://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "user-management.fullname" . }}
                  key: secret-key
