apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-management.fullname" . }}
  labels:
    {{- include "user-management.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ randAlphaNum 32 | b64enc | quote }}
