# user-management-app/helm/values.yaml
replicaCount: 1

image:
  repository: your-docker-repo/user-management-app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: "app.12.23.23.43.nip.io"
      paths:
        - path: /
          pathType: Prefix
  tls: []

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        postgresPassword: "postgres"
        username: "postgres"
        password: "postgres"
        database: "userdb"
